### ISSUE TITLE
adb / fastboot / flash_all.sh - Command not found.

### ISSUE THREAD

**Issue by charlesbarnes** [colstrom/android-butler#1]
charles@desktop-charles:~/Program Downloads/android-butler-master$ ./nexus7.sh
[sudo] password for charles: 
You are about to add the following PPA to your system:
 Ubuntu Nexus7 Desktop Installer
 A PPA which provides a desktop one-click solution for installing Ubuntu 13.04 on your Asus Nexus7 using Ubuntu 12.04, 12.10 or 13.04
 More info: https://launchpad.net/~ubuntu-nexus7/+archive/ubuntu-nexus7-installer
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpZ1Ujw6/secring.gpg' created
gpg: keyring`/tmp/tmpZ1Ujw6/pubring.gpg' created
gpg: requesting key AA2C09B3 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpZ1Ujw6/trustdb.gpg: trustdb created
gpg: key AA2C09B3: public key "Launchpad PPA for The Ubuntu Nexus7 Team" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
E: Type 'ain' is not known on line 3 in source list /etc/apt/sources.list.d/ubuntu-nexus7-ubuntu-nexus7-installer-oneiric.list
E: The list of sources could not be read.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Type 'ain' is not known on line 3 in source list /etc/apt/sources.list.d/ubuntu-nexus7-ubuntu-nexus7-installer-oneiric.list
E: The list of sources could not be read.
E: Unable to locate package android-tools-fastboot
E: Unable to locate package android-tools-adb
mkdir: cannot create directory `files': File exists
sudo: fastboot: command not found
tar (child): factory-image.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
cd: 25: can't cd to nakasi-jop40d
sudo: ./flash-all.sh: command not found
sudo: fastboot: command not found
sudo: adb: command not found
sudo: adb: command not found
sudo: adb: command not found
sudo: adb: command not found
sudo: fastboot: command not found
charles@desktop-charles:

**Comment by colstrom** [comment]
Pushed a series of patches that should resolve this, and a host of other issues.

Confirmed resolved on Linux Mint 14 (x86_64), let me know if you encounter further issues, or if it doesn't work properly on another distribution or architecture.
